@baseUrl = {{$dotenv ../API_URL}}
### Sign Up
POST {{baseUrl}}/signUp
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "TestPassword123!"
}

### Sign In
# @name signIn
POST {{baseUrl}}/signIn
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "TestPassword123!"
}

### Get User (using token from Sign In response)
GET {{baseUrl}}/getUser
Authorization: Bearer {{ signIn.response.body.AccessToken }}

### Refresh Token
POST {{baseUrl}}/refreshToken
Content-Type: application/json

{
  "refreshToken": "{{ signIn.response.body.RefreshToken }}"
}

### Sign Out
POST {{baseUrl}}/signout
Authorization: Bearer {{ signIn.response.body.AccessToken }}
